from __future__ import annotations

import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


import argparse
import json
import zipfile
from typing import Any

import numpy as np
import torch
import torch.distributed as dist

from project.generate import (
    _num_samples,
    _torch_load,
    lattice6_recover,
    load_model,
    load_spacegroup_masks,
    merge_sample_shards,
    wyckoff_sample_to_tables,
)
from project.train import (
    cleanup_distributed,
    is_main_process,
    resolve_device,
    set_seed,
    setup_distributed,
)
from project.utils import config as cfg
from project.utils.spg_info import spg_wyckoff_degrees_of_freedom, wyckoff_label_to_index


DEFAULT_TEMPLATE_PATH = cfg.OUTPUT_DIR / "postproc" / "new_orbit_templates.json"
DEFAULT_SAVE_DIR = cfg.OUTPUT_DIR / "new_template_samples_nocl"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate crystal structures from unseen occupied-orbit templates."
    )
    cfg.add_common_args(parser)
    cfg.add_model_args(parser)
    parser.add_argument("--checkpoint-path", type=str, default=str(cfg.CHECKPOINT_PATH))
    parser.add_argument(
        "--spacegroup-template-path",
        type=str,
        default=str(cfg.SPACEGROUP_TEMPLATE_PATH),
        help="Path to the Wyckoff coordinate-mask table.",
    )
    parser.add_argument("--new-template-path", type=Path, default=DEFAULT_TEMPLATE_PATH)
    parser.add_argument("--save-dir", type=Path, default=DEFAULT_SAVE_DIR)
    parser.add_argument("--structures-per-template", type=int, default=10)
    parser.add_argument(
        "--generation-batch-size",
        type=int,
        default=cfg.SAMPLE_BATCH_SIZE,
        help="Number of structures generated by each model.sample call on each GPU.",
    )
    parser.add_argument(
        "--space-groups",
        type=int,
        nargs="*",
        default=None,
        help="Optional subset of space groups. The default uses every group in the JSON file.",
    )
    parser.add_argument("--save-cifs", dest="save_cifs", action="store_true")
    parser.add_argument("--no-save-cifs", dest="save_cifs", action="store_false")
    parser.set_defaults(save_cifs=True)
    return parser


def load_new_templates(path: Path) -> dict[int, list[tuple[str, ...]]]:
    if not path.exists():
        raise FileNotFoundError(
            f"New-template file not found: {path}. Run postproc/sample_new_pattern.py first."
        )
    raw = json.loads(path.read_text(encoding="utf-8"))
    groups = raw.get("space_groups")
    if not isinstance(groups, dict):
        raise ValueError(f"{path} must contain a 'space_groups' dictionary.")

    templates: dict[int, list[tuple[str, ...]]] = {}
    for spg_text, records in groups.items():
        spg = int(spg_text)
        if not isinstance(records, list):
            raise ValueError(f"Templates for space group {spg} must be a list.")
        parsed: list[tuple[str, ...]] = []
        for template_index, record in enumerate(records):
            if not isinstance(record, dict) or "wyckoff_letters" not in record:
                raise ValueError(
                    f"Space group {spg}, template {template_index} has no wyckoff_letters."
                )
            letters = tuple(str(letter) for letter in record["wyckoff_letters"])
            if not letters:
                raise ValueError(f"Space group {spg}, template {template_index} is empty.")
            if letters != tuple(sorted(letters)):
                raise ValueError(
                    f"Space group {spg}, template {template_index} is not ordered a-to-z."
                )
            if int(record.get("orbit_count", len(letters))) != len(letters):
                raise ValueError(
                    f"Space group {spg}, template {template_index} has an invalid orbit_count."
                )
            parsed.append(letters)
        templates[spg] = parsed
    return templates


def make_generation_jobs(
    templates: dict[int, list[tuple[str, ...]]],
    structures_per_template: int,
    requested_space_groups: list[int] | None,
) -> list[dict[str, Any]]:
    if structures_per_template <= 0:
        raise ValueError("--structures-per-template must be positive.")

    available = set(templates)
    if requested_space_groups:
        selected_groups = list(dict.fromkeys(int(spg) for spg in requested_space_groups))
        missing = [spg for spg in selected_groups if spg not in available]
        if missing:
            raise KeyError(f"Space groups are absent from the new-template JSON: {missing}")
    else:
        selected_groups = sorted(available)

    jobs: list[dict[str, Any]] = []
    for spg in selected_groups:
        for template_index, letters in enumerate(templates[spg]):
            for sample_index in range(structures_per_template):
                jobs.append(
                    {
                        "space_group": spg,
                        "template_index": template_index,
                        "sample_index": sample_index,
                        "wyckoff_letters": letters,
                    }
                )
    if not jobs:
        raise ValueError("The selected space groups contain no new templates.")
    return jobs


def make_template_batch(
    jobs: list[dict[str, Any]],
    masks: dict[int, dict[str, Any]],
    max_inf_occ: int,
    device: torch.device,
) -> dict[str, torch.Tensor | list[list[str]]]:
    space_groups = []
    batch_index = []
    continuous_masks = []
    letter_ids = []
    token_dofs = []
    labels: list[list[str]] = []

    for local_index, job in enumerate(jobs):
        spg = int(job["space_group"])
        letters = tuple(job["wyckoff_letters"])
        if spg not in masks:
            raise KeyError(f"Space group {spg} is missing from the coordinate-mask table.")
        dof_map = spg_wyckoff_degrees_of_freedom[str(spg)]
        occurrences: dict[str, int] = {}
        space_groups.append(spg)
        labels.append(list(letters))

        for letter in letters:
            if letter not in dof_map:
                raise KeyError(f"Wyckoff letter {letter!r} is invalid for space group {spg}.")
            if letter not in masks[spg]:
                raise KeyError(f"No coordinate mask for space group {spg}, letter {letter}.")
            count = occurrences.get(letter, 0) + 1
            if count > max_inf_occ:
                raise ValueError(
                    f"Space group {spg} template contains more than {max_inf_occ} copies of {letter}."
                )
            occurrences[letter] = count

            dof = int(dof_map[letter])
            coord_mask = np.asarray(masks[spg][letter], dtype=np.float32).reshape(3)
            if int(np.rint(coord_mask.sum())) != dof:
                raise ValueError(
                    f"Mask for space group {spg}, letter {letter} does not match dof={dof}."
                )
            batch_index.append(local_index)
            continuous_masks.append(coord_mask)
            letter_ids.append(int(wyckoff_label_to_index[letter]))
            token_dofs.append(dof)

    return {
        "space_group": torch.as_tensor(space_groups, dtype=torch.long, device=device),
        "batch_index": torch.as_tensor(batch_index, dtype=torch.long, device=device),
        "continuous_mask": torch.as_tensor(
            np.asarray(continuous_masks), dtype=torch.float32, device=device
        ),
        "wyckoff_letter": torch.as_tensor(letter_ids, dtype=torch.long, device=device),
        "wyckoff_dof": torch.as_tensor(token_dofs, dtype=torch.long, device=device),
        "wyckoff_labels": labels,
    }


@torch.no_grad()
def sample_jobs(
    model,
    jobs: list[dict[str, Any]],
    masks: dict[int, dict[str, Any]],
    args: argparse.Namespace,
    device: torch.device,
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    chunks: list[dict[str, Any]] = []
    metadata: list[dict[str, Any]] = []
    total_batches = (len(jobs) + args.generation_batch_size - 1) // args.generation_batch_size

    for start in range(0, len(jobs), args.generation_batch_size):
        chunk_jobs = jobs[start : start + args.generation_batch_size]
        template_batch = make_template_batch(chunk_jobs, masks, args.max_inf_occ, device)
        sample = model.sample(template_batch, device=device)
        cpu_sample = {key: value.cpu() for key, value in sample.items()}
        cpu_sample["wyckoff_labels"] = template_batch["wyckoff_labels"]
        chunks.append(cpu_sample)
        metadata.extend(chunk_jobs)
        batch_number = start // args.generation_batch_size + 1
        print(f"rank batch: {batch_number}/{total_batches}")

    return merge_sample_shards(chunks), metadata


def save_generated_cifs(
    samples: dict[str, Any],
    metadata: list[dict[str, Any]],
    args: argparse.Namespace,
) -> None:
    from project.utils.dataset_utils import tables_to_crystal

    if _num_samples(samples) != len(metadata):
        raise ValueError("Sample tensors and generation metadata have different lengths.")

    cif_dir = args.save_dir / "cifs"
    cif_dir.mkdir(parents=True, exist_ok=True)
    mask_table = _torch_load(Path(args.spacegroup_template_path), torch.device("cpu"))
    structure_info: dict[str, Any] = {}
    saved = 0

    for index, job in enumerate(metadata):
        spg = int(samples["space_group"][index].item())
        if spg != int(job["space_group"]):
            raise ValueError(f"Space-group mismatch at generated sample {index}.")
        discrete_tab, continuous_tab, letters, dofs = wyckoff_sample_to_tables(samples, index)
        if len(discrete_tab) == 0:
            continue
        lattice = lattice6_recover(samples["lattice"][index]).numpy()
        filename = (
            f"sg{spg}_template{int(job['template_index']):03d}_"
            f"sample{int(job['sample_index']):03d}.cif"
        )
        try:
            result = tables_to_crystal(
                discrete_tab=discrete_tab,
                continuous_tab=continuous_tab,
                wyckoff_letters=letters,
                wyckoff_dofs=dofs,
                spg_number=spg,
                lattice_const=lattice,
                mask=mask_table,
            )
            if result is None:
                continue
            structure, info = result
            structure.to(filename=str(cif_dir / filename))
            structure_info[filename] = {
                "source_template_index": int(job["template_index"]),
                "source_wyckoff_letters": list(job["wyckoff_letters"]),
                "generated_wyckoff_letters": letters,
                "structure_info": info,
            }
            saved += 1
        except Exception as exc:
            print(f"skip {filename}: {exc}")

    (args.save_dir / "total.json").write_text(
        json.dumps(structure_info, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    zip_path = args.save_dir / "cifs.zip"
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for cif_path in sorted(cif_dir.glob("*.cif")):
            archive.write(cif_path, arcname=cif_path.name)
    print(f"saved CIFs: {saved}/{len(metadata)} -> {cif_dir}")


def run(args: argparse.Namespace) -> None:
    if args.generation_batch_size <= 0:
        raise ValueError("--generation-batch-size must be positive.")

    distributed, local_rank, rank, world_size = setup_distributed()
    main_process = is_main_process(distributed, rank)
    set_seed(args.seed + rank)
    device = (
        torch.device(f"cuda:{local_rank}")
        if distributed and torch.cuda.is_available()
        else resolve_device(args.device)
    )

    try:
        templates = load_new_templates(args.new_template_path)
        jobs = make_generation_jobs(
            templates,
            args.structures_per_template,
            args.space_groups,
        )
        local_jobs = [job for index, job in enumerate(jobs) if index % world_size == rank]
        masks = load_spacegroup_masks(args.spacegroup_template_path, device)
        model, checkpoint = load_model(args, device)

        args.save_dir.mkdir(parents=True, exist_ok=True)
        local_samples, local_metadata = sample_jobs(model, local_jobs, masks, args, device)
        shard_path = args.save_dir / f"new_template_samples_rank{rank}.pt"
        torch.save(
            {
                "samples": local_samples,
                "metadata": local_metadata,
                "checkpoint_epoch": checkpoint.get("epoch"),
                "rank": rank,
                "world_size": world_size,
                "args": vars(args),
            },
            shard_path,
        )
        print(f"rank={rank} saved shard: {shard_path}")

        if distributed:
            dist.barrier()

        if main_process:
            if distributed:
                shards = [
                    torch.load(
                        args.save_dir / f"new_template_samples_rank{shard_rank}.pt",
                        map_location="cpu",
                        weights_only=False,
                    )
                    for shard_rank in range(world_size)
                ]
                samples = merge_sample_shards([shard["samples"] for shard in shards])
                metadata = [job for shard in shards for job in shard["metadata"]]
            else:
                samples = local_samples
                metadata = local_metadata

            output_path = args.save_dir / "new_template_samples.pt"
            torch.save(
                {
                    "samples": samples,
                    "metadata": metadata,
                    "checkpoint_epoch": checkpoint.get("epoch"),
                    "args": vars(args),
                },
                output_path,
            )
            print(
                f"generated {_num_samples(samples)} structures from "
                f"{len(jobs) // args.structures_per_template} templates -> {output_path}"
            )
            if args.save_cifs:
                save_generated_cifs(samples, metadata, args)

        if distributed:
            dist.barrier()
    finally:
        cleanup_distributed(distributed)


def main() -> None:
    args = build_parser().parse_args()
    run(args)


if __name__ == "__main__":
    main()
